.TH MEOW 1 MEOW\-2.0.7
.SH NAME
Meowlang \- New language for Devlopers to make fun with it.
.SH SYNOPSIS
.B Meow
.RB [ \-h
.IR help ]
.RB [ \-v
.IR version ]
.RB [ \-e
.IR commandline ]
.RB [ \-p
.IR pointer ]
.P
.BR Meow " use it for fun !.."
.SH SESCRIPTION
.B Meow
[--] [programfile] [arguments]

.SH OPTIONS
.TP
.B \-h
help to use it
.TP
.B \-v
print the version number
.TP
.B \-e
one line of script
.TP
.B \-p
findout pointer name
.SH AUTHOR
.B nimacpp
.SH COPYRIGHT
.B
MIT , Copyright (c) 2024 Meowlang
